CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; 
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS APPLICATION_USER 
(
     UUID UUID DEFAULT UUID_GENERATED_V4()
    ,USERNAME VARCHAR NOT NULL
    ,PASSWORD VARCHAR NOT NULL
    PRIMARY KEY (UUID)
)

INSERT INTO APPLICATION_USER (USERNAME, PASSWORD)
VALUES ('renan', crypt('admin', 'my_salt'));